//
//Each new term in the Fibonacci sequence is generated by
// adding the previous two terms. By starting with 1 and 2,
// the first 10 terms will be:

// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

// By considering the terms in the Fibonacci sequence whose values do
// not exceed four million, find the sum of the even-valued terms.
//1 + 2 = 3
//2 + 3 = 5
//3 + 5 = 8
//5 + 8 = 13
//8 + 13 = 21
//13 + 21 = 34
//21 + 34 = 55
//34 + 55 = 89
//55 + 89 = 144

var cannotExceed = 4000000;
var x = 1,
    y = 2,
    substitute = 0,
    evenSum = 0;

while (y < cannotExceed) {
  //console.log("x: ", x, "y: ", y, "i: ", i, "sum: ", evenSum);
  substitute = x + y;
  x = y;
  y = substitute;
  if (x%2===0) evenSum += x;
};

console.log(evenSum);
//4613732
